---
title: "進化社会学課題3"
author: "工科太郎"
date: "`r format(Sys.Date(),'%Y年%m月%d日')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 課題の内容

A) 内容バイアスの数理モデルにおいて、$B=0.1,0.3,0.5$の3つの値に対して、形質cの頻度$p_t$の時間変化のグラフを描くコードを作成しなさい。ただし、差分方程式の数値解と微分方程式による近似解の両方をプロットしなさい。前者を点で、後者を曲線でプロットすること。初期値は$p_0=0.1$、世代数は$t=0\sim 100$とする。

```{r assignment-3-A}
# ここにコードを書く


# 数値計算
gn <- 100
B <- c(0.1,0.3,0.5,-0.1,-0.3,-0.5)
p <- matrix(nrow=length(B),ncol=gn+1)
p[,1] <- rep(c(0.1,0.9),each=3)
for(t in 1:gn) {
  p[,t+1] <- p[,t] + B*p[,t]*(1-p[,t])
}

# 近似解を与える関数の定義
p_ana <- function(p0,B,t) {
  solution <- p0*exp(B*t)/(1-p0+p0*exp(B*t))
  return(solution)
}

# グラフのプロット
for(i in 1:3) {
  plot(0:gn,p[i,],col=i,xlim=c(0,gn),ylim=c(0,1),xlab='Generation',ylab='Frequency')
  par(new=T)
  curve(p_ana(0.1,B[i],x),xlim=c(0,gn),ylim=c(0,1),xlab='',ylab='')
  par(new=T)
}
```

B) 上記Aと同様、$B=-0.1,-0.3,-0.5$の値に対して形質cの頻度$p_t$の時間変化のグラフを描くコードを作成しなさい。ただしこちらは初期頻度を$p_0=0.9$としなさい。それ以外はAと同じです。

```{r assignment-3-B}
# ここにコードを書く
for(i in 4:6) {
  plot(0:gn,p[i,],col=i,xlim=c(0,gn),ylim=c(0,1),xlab='Generation',ylab='Frequency')
  par(new=T)
  curve(p_ana(0.9,B[i],x),xlim=c(0,gn),ylim=c(0,1),xlab='',ylab='')
  par(new=T)
}
```

注：工夫すれば6×101の行列を使ってAとBの数値計算を一つのコードで行うことができます。
